# Generated by Django 4.2.3 on 2023-11-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=50),
        ),
    ]
