# Generated by Django 4.2.3 on 2023-11-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0003_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
