# Generated by Django 4.2.3 on 2023-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0004_uicustomization_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=None, null=True),
        ),
    ]
