# Generated by Django 4.2.3 on 2023-10-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Teacher', 'Teacher')], max_length=10),
        ),
    ]
