# Generated by Django 4.2.3 on 2023-11-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SchoolManage', '0005_custompermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'verbose_name': 'Roles and permissions'},
        ),
        migrations.RemoveField(
            model_name='custompermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='custompermission',
            name='permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
