# Generated by Django 4.2.3 on 2023-11-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SchoolManage', '0005_alter_countries_options_alter_role_name'),
    ]

    operations = [
     
        migrations.RemoveField(
            model_name='custompermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='custompermission',
            name='permission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
    ]
