# Generated by Django 4.2.3 on 2023-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('snapchat', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('work_time', models.CharField(blank=True, max_length=100, null=True)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('google_map_iframe', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('login_timeout', models.PositiveIntegerField(blank=True, null=True)),
                ('about_small', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('head_tag', models.TextField(blank=True, null=True)),
                ('footer_tag', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
