# Generated by Django 4.2.3 on 2023-11-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SchoolManage', '0006_alter_countries_options_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
    ]
