# Generated by Django 4.2.3 on 2023-11-25 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0006_alter_parent_children_alter_student_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(limit_choices_to={'role__name__exact': 'student'}, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
