# Generated by Django 4.2.3 on 2023-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0006_generalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'General Settings'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
