# Generated by Django 4.2.3 on 2023-11-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0007_alter_parent_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(to='SchoolManage.parent'),
        ),
    ]
