# Generated by Django 4.2.3 on 2023-11-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0007_alter_countries_options_role_permission'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='custompermission',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='can_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
