# Generated by Django 4.2.3 on 2023-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0008_remove_parent_children_alter_student_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Date_joined',
            field=models.DateField(default=None, null=True),
        ),
    ]
