# Generated by Django 4.2.3 on 2023-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0009_alter_countries_options_remove_role_permission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': 'Course Section', 'verbose_name_plural': 'Course Sections'},
        ),
        migrations.AlterModelOptions(
            name='custompermission',
            options={'verbose_name': 'Custom Permission', 'verbose_name_plural': 'Custom Permissions'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'ExamResult', 'verbose_name_plural': 'ExamResults'},
        ),
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'GeneralSetting', 'verbose_name_plural': 'GeneralSettings'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonorder',
            options={'verbose_name': 'Lesson Order', 'verbose_name_plural': 'Lesson Orders'},
        ),
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'verbose_name': 'LessonPlan', 'verbose_name_plural': 'LessonPlans'},
        ),
        migrations.AlterModelOptions(
            name='livemeeting',
            options={'verbose_name': 'LiveMeeting', 'verbose_name_plural': 'LiveMeetings'},
        ),
        migrations.AlterModelOptions(
            name='onlineexam',
            options={'verbose_name': 'OnlineExam', 'verbose_name_plural': 'OnlineExams'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionchoice',
            options={'verbose_name': 'Question Choice', 'verbose_name_plural': 'Question Choices'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'ShoppingCart', 'verbose_name_plural': 'ShoppingCarts'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'StudentAnswer', 'verbose_name_plural': 'StudentAnswers'},
        ),
        migrations.AlterModelOptions(
            name='studentattempt',
            options={'verbose_name': 'StudentAttempt', 'verbose_name_plural': 'StudentAttempts'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name': 'StudentProgress', 'verbose_name_plural': 'StudentProgresses'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='submitedhomworks',
            options={'verbose_name': 'SubmitedHomwork', 'verbose_name_plural': 'SubmitedHomworks'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'Syllabus', 'verbose_name_plural': 'Syllabi'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'verbose_name': 'Video Lesson', 'verbose_name_plural': 'Video Lessons'},
        ),
        migrations.RemoveField(
            model_name='livemeeting',
            name='meeting_url',
        ),
        migrations.AlterField(
            model_name='role',
            name='custom_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Custom Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=50, verbose_name='Role'),
        ),
    ]
