# Generated by Django 4.2.3 on 2023-11-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0009_student_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Date_joined',
        ),
    ]
