# Generated by Django 4.2.3 on 2023-11-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManage', '0010_remove_student_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
